### ISSUE TITLE
Sensors missing on BGC-Argo

### ISSUE THREAD

**Issue by OrensOceanOPS** [OceanOPS/web-dashboard#111]
### Context/theme

Argo

### Describe the bug

Several floats with BGC-Sensors are not well registered at OceanOPS weheras the information exists at the level of the GDAC.

As an example, float number 3901578 has meta file,  profile and bio index files but no sensors are declared at OceanOPS. 

![image](https://github.com/OceanOPS/web-dashboard/assets/134387956/3fac1699-3e64-4a21-87b8-ae4aa2f5edbd)

![image](https://github.com/OceanOPS/web-dashboard/assets/134387956/a11d565c-c0d2-4526-a5e1-ac12b4dba8e5)

**Comment by MKrieger29** [comment]
The float 3901578 
- notified on 23 November 2022
- Deployed on 16 March 2023

=> this float never appeared in the daily mail "Argo Missing GDAC" 

(Checked in the OceanOPS DB:  
select * from nc_notification where nc_topic_id = 162 and description like '%3901578%';
=> 0 result)

The meta file exists, with sensor info: 
[Link to the meta.nc](https://data-argo.ifremer.fr/dac/bodc/3901578/3901578_meta.nc)

**Comment by MKrieger29** [comment]
I tried to find other examples in the OceanOPS DB (linked to that issue). 
float 1902597 (status on 29 August 2023): 0 sensor info
![image](https://github.com/OceanOPS/web-dashboard/assets/74649916/65d02835-a2e4-4d96-b353-b46fbb46e7d3)

A meta file exists, but no notif about that (because already notified). The float is not up to date: 
![image](https://github.com/OceanOPS/web-dashboard/assets/74649916/a8f32d05-87d9-4916-affc-6b0a76b62254)
![image](https://github.com/OceanOPS/web-dashboard/assets/74649916/b32f5a88-bf4e-46f0-b273-ef1ded7a03c3)

**Comment by MKrieger29** [comment]
Pour résumer, je pense que le problème vient du fait que : 
- les flotteurs sont notifiés dès l'enregistrement. Ils ont tout de suite le statut REGISTERED
- Ils passent donc au travers du filet de la routine quotidienne 'Argo missing GDAC' et ne sont jamais mis à jour. 
A confirmer avec @OrensOceanOPS  et @vturpin

**Comment by OrensOceanOPS** [comment]
C'est mon adresse mail perso!
Du coup faut faire quoi? Rentrer à la main ou faire des modifs du code?

________________________________
De : MagaliKrieger ***@***.***>
Envoyé : mardi 29 août 2023 16:27
À : OceanOPS/web-dashboard ***@***.***>
Cc : OrensOceanOPS ***@***.***>; Mention ***@***.***>
Objet : Re: [OceanOPS/web-dashboard] Sensors missing on BGC-Argo (Issue #111)


Pour résumer, je pense que le problème vient du fait que :

  *   les flotteurs sont notifiés dès l'enregistrement. Ils ont donc tout de suite le statut REGISTERED
  *   Ils passent donc au travers du filet de la routine quotidienne 'Argo missing GDAC' et ne sont donc jamais mis à jour.
A confirmer avec @OrensOceanOPS<https://github.com/OrensOceanOPS> et @vturpin<https://github.com/vturpin>

**Comment by vturpin** [comment]
Revue of sensor metadata has been done and will be regularly repeated before AST and ADMT.

This situation should be identified and fixed by this procedure.

Issue can e closed
