### ISSUE TITLE
Change definition of Argo-BGC

### ISSUE THREAD

**Issue by vturpin** [OceanOPS/web-dashboard#118]

**Comment by vturpin** [comment]
Currently, Argo-BGC include every float measuring any BGC variable (O2, CHLA, BBP, Nitrate, PH, Irradiance). This include many floats measuring T/S/O2 only.

We have been requested to change that definition to exclud the float measuring T/S/O2 only. This send the wrong message to the community on the performance of Argo BGC (aiming to maintain 1000 floats measure the 6 BGC parameters).

To do so we need to 

1. Update our data base to exclud T/S/O only from BGC.
2. Reprocess all KPI for the BGC network
3. Update the network allocation procedure to make sure next T/S/O2 only float is not tagged as BGC. This allocation is done when the ptf (Argo float) is uploaded (wizzard, upload, etc. ) and, maybe when we receive the observation (e.g. in the case of a float notified with only a T/S sensor but we discover that there is BGC parameters in the data, maybe in that case we tag this float with the network "Argo BGC").

**Comment by vturpin** [comment]
We just checked with Anthonin ;) 

With regard to point 3. 
The allocation procedure is based on the sensor model (maybe sensor type) declared, not the observations.

**Comment by vturpin** [comment]
After discussion:

We keep Argo BGC as it is.
We create the "Argo BGC - multiparam" network that exclude "T/S/O only".
We create the Argo BGC - full" that consider only float with 5 or 6 paramters.

We create the implementation KPI for those networks (activity, density, intensity).

Note that for the three BGC networks we will use different "green" for the lines in the KPIs.

- light green for the "Argo BGC" network
- standard green for the "Argo BGC - multiparam" network
- dark green for the "Argo BGC - full" network

We also improve the definition displayed on the KPIs. Please check the [wiki](https://github.com/OceanOPS/helpdesk/wiki/Argo-networks#argo-bgc) to find the definitions.

**Comment by vturpin** [comment]
This is related to this issue: https://github.com/OceanOPS/web-dashboard/issues/87
but only the KPI aspect.
The maps side of the issue #87 should be pushed in another ticket when this issue is implemented.

**Comment by vturpin** [comment]
@tomlatter 

here is the mapping between "BGC parameters", "sensor type" and "variables"


**BGC parameter**        /// **sensor type**  /// **variable**
chla                               /// FLUOROMETER_CHLA /// chlorophyl_concentration 
suspended particules   /// BACKSCATTERINGMETER_BBP, FLUOROMETER_CDOM /// backscatter, Fluorescence (DOM)
nitrate                          /// SPECTROPHOTOMETER_NITRATE /// NO3- (nitrate)
oxygen                        /// DOXY_OPTODE, DOXY, DOXY_IDO  /// oxygen, dissolved
ph                               /// TRANSISTOR_PH  /// pH
irradiance                   /// RADIOMETER_DOWN_IRR, RADIOMETER_PAR  /// irradiance,photosynthetical active radiation


Maybe the best for us is to use the variables instead of the sensor_type. At least it is more comprehensive to map a parameter with a variable.

The rule is : 
If a float is linked to one of these variables (or sensor type, depending on your choice) then the BGC parameter is measured by the float.

Let me know if this is unclear.
V.

**Comment by tomlatter** [comment]
@vturpin on peut donc ignorer les types suivants pour le full bcg? 
SPECTROPHOTOMETER_BISULFIDE
TRANSMISSOMETER_CP<nnn>
RADIOMETER_UP_RAD<nnn>
BACKSCATTERINGMETER_TURBIDITY

**Comment by tomlatter** [comment]
@vturpin est-ce que tu pourrais me donner une ordre d'idée de la quantité de flotteurs Full BGC? Si je te dis 74 ça te semble correct?

**Comment by tomlatter** [comment]
94 si j'inclus les 4 types cités plus haut, 74 sans

**Comment by vturpin** [comment]
Cette carte donne 275 flotteurs...
https://www.ocean-ops.org/share/Argo/Maps/bgc-var56-countries.pdf

Donc 74 c'est un peu juste je pense.
Cette carte peut être utile aussi ; https://www.ocean-ops.org/share/Argo/Maps/bgc-var56-countries.pdf

**Comment by vturpin** [comment]
J'ai eu le go de la chair d'Argo par rapport à ce ticket.
All good.

**Comment by vturpin** [comment]
Solved before AST 24
