### ISSUE TITLE
Login not "valid" on all boards

### ISSUE THREAD

**Issue by hkleta** [OceanOPS/web-dashboard#15]
### Describe the bug

When loging in on the general OceanOPS board and then moving to the SOT board, a new login in required, although the login credetials are exactly the same then o nthe general board.
Must be corrected. Login should be login, regardless on board.

**Comment by anthoninlize** [comment]
Ticking the box "Auto connect on next visit" while logging in is there for that. If not working, certainly due to conflict with your browser cookie policy (which I guess can be set by your org, in which case we can't do anything about it).

Any luck?

**Comment by anthoninlize** [comment]
Ticking the box "Auto connect on next visit" while logging in is there for that. If not working, certainly due to conflict with your browser cookie policy (which I guess can be set by your org, in which case we can't do anything about it).

Any luck?
