### ISSUE TITLE
Small screens/definitions improvement

### ISSUE THREAD

**Issue by anthoninlize** [OceanOPS/web-dashboard#2]
Reported by @emmasteventon

I’ve noticed a functionality issue with the search box in OceanOps that I wanted to raise. 
 
I’m working from a laptop and it seems like the website isn’t optimised quite right for a smaller screen…
 
The screen shot below shows my screen with the red dashed line being the very bottom. If I want to expand the advanced filters button I get only <0.5cm to view the scrolling list which is really annoying. I appreciate you can use the Find a filter search box, but you would have to know what all the options are in order to do this…which most people don’t. Even if I can enter a known search field, Program for example, it doesn’t actually appear in the small space below, you still have to use those tiny arrows to the right to see it.
 
Could the whole advanced search window just be fully scrollable from top to bottom? I don’t think it’s important to keep the top section in fixed view at all times. 
 
I don’t know if this is the same across all OceanOps programmes but I noticed it working like this in the DBCP area… 

![image](https://user-images.githubusercontent.com/17119571/171608678-e73712ac-53a3-448e-a1a0-12d6ac7448ec.png)

**Comment by tomlatter** [comment]
Scrollable area has been enlarged to include the quick fields above.

**Comment by anthoninlize** [comment]
Works well, thanks. Closing.
