### ISSUE TITLE
'Select-all' box not working in platform list

### ISSUE THREAD

**Issue by emmasteventon** [OceanOPS/web-dashboard#3]
I loaded up the UK drifting buoys and 30 rows were listed. When trying to select all the records to export, I clicked the 'select all' tick box on the top row but this only selected rows 12-22 and 24-29. For some reason rows 1-11, 23 and 30 were excluded... 
Screenshot attached

<img width="543" alt="OceanOps GUI error" src="https://user-images.githubusercontent.com/103102833/176638548-9abfe5b3-9844-4a59-92aa-a4acf4aa9dc6.PNG">

**Comment by anthoninlize** [comment]
Hi @emmasteventon
Can you confirm it is fixed? Thanks

**Comment by emmasteventon** [comment]
Hi @anthoninlize  - I've just tried and can confirm it now all looks ok. 
Many thanks for fixing
