### ISSUE TITLE
Cruise reference

### ISSUE THREAD

**Issue by MKrieger29** [OceanOPS/web-dashboard#35]
### Context/theme

Integrated (OceanOPS), Argo, DBCP, SOT, GO-SHIP, OceanSITES, GLOSS, OceanGliders

### Describe the bug

The reference  of the cruise is not the same in the little pop-up and in the cruise inspect window: 
![image](https://user-images.githubusercontent.com/74649916/226610505-8e5356aa-e848-4357-9259-1199c6228671.png)

**Comment by anthoninlize** [comment]
Fixed. I updated TMP ref yesterday to get real cruise IDs, the GIS layer did not follow.

@MartinOceanOPS for information
