### ISSUE TITLE
autocompletion program field

### ISSUE THREAD

**Issue by RomainCancouet** [OceanOPS/web-dashboard#59]
### Context/theme

Argo

### Description of the desired feature

the autocompletion feature is not implemented/working for the program field

![image](https://github.com/OceanOPS/web-dashboard/assets/61823190/d7f77690-07b2-4e53-95d1-459433e86faa)

this may be the case for other fields, or other parts of the query search but I cannot remember which ones now

### Suggested solution

implement autocompletion for all fields and query search

**Comment by anthoninlize** [comment]
Hi @RomainCancouet 
it's probably fixed, can you try please?

**Comment by RomainCancouet** [comment]
Hi @anthoninlize yes I confirm thanks
