### ISSUE TITLE
Quick Serach delivers results which are wrong

### ISSUE THREAD

**Issue by hkleta** [OceanOPS/web-dashboard#6]
**Context/Theme**
Only at OST theme tested

**Describe the bug**
When entering something in the quick search entry field, the system starts to search while typing.
By that the first found entry when hitting enter is opeed / shown, although it does not necessarily represent what has been searched for.
E.g. search for the IMO 9508901.
Whily typing the vessel "rio de janeiro" is shown and selected, although that vessel does nothave the IMO number that was entered.
Mjust be corrected, as otherwisse there is the danger that entries are selected and worst case changed or used although not fullfilling the info that has been searched for.

**Priority**
High priority as with such unpredictable behaviour the acceptance of the tool will suffer.

**Comment by anthoninlize** [comment]
'rio de janeiro' has the IMO 9508902. So it's normal for it to appear as you type 9508901 until the last digit.
It disappears when adding the 1 at the end, when completing the typing.
The issue lies in the fact that you're too fast for the search :).

Suggested fix: adding a clearer indicator when the search is active, and disable the selection as well when active searching.

**Comment by hkleta** [comment]
Hi,

wanted to answwer, but I cannot find the issue anymore in Github?
-> where is it gone? Een when searching for me as author nothing shows up...

The "presearch" can be helpful, but only when I hit enter, the "real" search should be started, and only those results should be shown then...

And that is right now not the case, and teh results differ depending on the internetlink, the speed of tying, and probably the load on your system.

What is needed is a reproducible result.

Best regards,

Henry

-- 
Leiter Maritime Messnetzgruppe / Marine Network Manager
Deutscher Wetterdienst, TI 21 C
Bernhard-Nocht-Str. 76, D-20359 Hamburg
Tel: +49(0)69 8062-6310, Fax: +49(0)69 8062-11980

________________________________________
Von: Anthonin Lizé ***@***.***>
Gesendet: Freitag, 16. September 2022 12:09
An: OceanOPS/web-dashboard
Cc: hkleta; Author
Betreff: Re: [OceanOPS/web-dashboard] Quick Serach delivers results which are wrong (Issue #6)

'rio de janeiro' has the IMO 9508902. So it's normal for it to appear as you type 9508901 until the last digit.
It disappears when adding the 1 at the end, when completing the typing.
The issue lies in the fact that you're too fast for the search :).

Suggested fix: adding a clearer indicator when the search is active, and disable the selection as well when active searching.

—
Reply to this email directly, view it on GitHub<https://ofcsg2dvf1.dwd.de/fmlurlsvc/?fewReq=:B:JVI2PTg0Nip6MT4iPCplaDE8PTY8PSp/ZWtibXh5fmkxOTw1Pjk6PG05Ozpob2o0PT04bzw4O2hqaDw5NDhpPD5obTs/b2o/Pyp4MT06Oj8/Pj8+Oz8qfWVoMT40S01JVHtPPDw5OTo1IT40S01JVHtIPDw5OTo1Kn5vfHgxRGlifnUiR2BpeG1MaHtoImhpKm8xOT4qZGhgMTw=&url=https%3a%2f%2fgithub.com%2fOceanOPS%2fweb-dashboard%2fissues%2f6%23issuecomment-1249181057>, or unsubscribe<https://ofcsg2dvf1.dwd.de/fmlurlsvc/?fewReq=:B:JVI2PTg0Nip6MT4iPCplaDE8PTY8PSp/ZWtibXh5fmkxaT5oOG4/OT9vajw6Ozw/NGhvaGloP21ubTU7ajs9ODw6NDhtP2k9NCp4MT06Oj8/Pj8+Oz8qfWVoMT40S01JVHtPPDw5OTo1IT40S01JVHtIPDw5OTo1Kn5vfHgxRGlifnUiR2BpeG1MaHtoImhpKm8xOT4qZGhgMTw=&url=https%3a%2f%2fgithub.com%2fnotifications%2funsubscribe-auth%2fAYSGZAOMTM4DYGVTHNIF74DV6RBL5ANCNFSM6AAAAAAQOFORTE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

----------
Hinweis (DWD): Mindestens eine URL in dieser E-Mail wurde vom Schadsoftware-Erkennungssystem als potentiell gefährlich eingestuft und so umgeschrieben, dass ein Klick darauf diese zunächst auf gefährliche Downloads hin untersucht, bevor Inhalte angezeigt werden. Die Analyse erfolgt ohne menschliches Zutun voll automatisiert. Der Datenschutz ist gewährleistet. Es kann einige Sekunden dauern, bis die Inhalte angezeigt werden.
Der Originalabsender dieser E-Mail ist: ***@***.*** Wenn Ihnen dieser unbekannt ist, so sollten Sie die enthaltenen Links nicht anklicken.

**Comment by anthoninlize** [comment]
I'm replying to the issue there, it's still visible.

Result is reproducible, it's not the point here. We won't reinvent the semantic of the quick search. We have users (including us) that expect to access the first result when pressing enter. 
When I type in my search bar on the web browser and hit enter, I expect the browser to load the first result, not to display a definitive search, that would make me click another time. And I wait I bit more on slow connection. It's the same here.
So ok to indicate the search is ongoing as I suggested, maybe optimise where it's possible, but not to redefine the behaviour.

And side note: as long as the system and dynamic and metadata change, research results are susceptible to change. So reproducible result is not totally feasible anyway there.

**Comment by hkleta** [comment]
Sorry to disagree.
When entering anything in the searchbar of a webbrowser and I hit enter, I get a list of results of that search. Not the first entry.
And when a search does not have any results, opening "something" is simply wrong.
Is a bug, must be corrected.

**Comment by tomlatter** [comment]
Hi Henry

I have managed to hack the behaviour of the search boxes so that the options will be cleared during loading, so that any extra letter typed empties previous results, so that pressing "Enter" will not select anything until the new results are loaded.

There will also be a spinner during the loading process to make it more obvious.

I think these solutions will avoid any wrong selections.

Best
Thomas
