### ISSUE TITLE
Agency table empty

### ISSUE THREAD

**Issue by MKrieger29** [OceanOPS/web-dashboard#60]
### Context/theme

Integrated (OceanOPS), Argo, DBCP, SOT, GO-SHIP, OceanSITES, GLOSS, OceanGliders

### Describe the bug

When we search for agencies, the table is empty, even if results are found. See screenshot: 
![image](https://github.com/OceanOPS/web-dashboard/assets/74649916/f59778c9-a111-4aee-b4c2-0c7df89f14c2)

**Comment by anthoninlize** [comment]
Fixed
