### ISSUE TITLE
Add Glider name and SN to request ID feedback

### ISSUE THREAD

**Issue by vturpin** [OceanOPS/web-dashboard#62]
### Context/theme

OceanGliders

### Description of the desired feature

When requesting an ID through request id.
for OceanGLiders, name of the glider and serial number is requested (manatory).
The summary email only provide the WMO ID (and other information) but not the name and S.N that are essential to identify which WMO ID goes to wich glider when you request many at a time.

The desired feature should provide WMO ID, Program, glider name and SN (amongst other things).

**Comment by anthoninlize** [comment]
Done and released
