### ISSUE TITLE
Cruise update: Old/New editor

### ISSUE THREAD

**Issue by MKrieger29** [OceanOPS/web-dashboard#77]
### Context/theme

Integrated (OceanOPS)

### Describe the bug

If we want to update cruise metadata, depending on where we click, the cruise editor can be the "old" one, or the new one. 
"Edit" of the Inspect cruise window => "Old" cruise editor
Edit of the table => New editor

We should always reach the new cruise editor

**Comment by MKrieger29** [comment]
Save draft cruise plan > Old cruise editor 
![image](https://github.com/OceanOPS/web-dashboard/assets/74649916/47645fac-a1dc-4a26-b9c2-a1a87a361e99)

**Comment by anthoninlize** [comment]
Also happening when editing from inspect
