### ISSUE TITLE
'30 day history' button not working

### ISSUE THREAD

**Issue by emmasteventon** [OceanOPS/web-dashboard#8]
When clicking on a ship from the map view and opening up the new menu to explore the station, the 30 day history button doesn't seem to do anything when clicked. I've tried it for a few UK ships but it doesn't work for any of them...

![image](https://user-images.githubusercontent.com/103102833/191544125-b24dace8-797a-4722-bb2e-c8ceab177715.png)

**Comment by anthoninlize** [comment]
Temporarily fixed: known bugs on time-enabled layer but no permanent solution yet. To be investigated. In the meantime a manual operation on my side can punctually fix it.

![image](https://user-images.githubusercontent.com/17119571/191774804-a999dc49-10fb-42d7-8a09-7b4e23c2947b.png)

**Comment by anthoninlize** [comment]
Issue due to the time slider property not getting the proper end of time extent - forced to today's date to work around.
