### ISSUE TITLE
Update cruise WKT no longer works

### ISSUE THREAD

**Issue by MartinOceanOPS** [OceanOPS/web-dashboard#88]
### Context/theme

Integrated (OceanOPS)

### Describe the bug

After drawing geometry for T6MRORR96I the WKT was not taken over into the draft cruise plan and it was at later stage also not possible to update the geometry.

**Comment by anthoninlize** [comment]
@MartinOceanOPS would you mind indicating the desired WKT update here? I'd like to test it on my side. thks

**Comment by anthoninlize** [comment]
Fixed and published
