### ISSUE TITLE
Deep network not working

### ISSUE THREAD

**Issue by RomainCancouet** [OceanOPS/web-dashboard#91]
### Context/theme

Argo

### Describe the bug

Hello,
Some floats registered with model ARVOR_D (so family deep) are not included in the Deep Network, so they are missing on maps 
eg 1902621
4902637

**Comment by vturpin** [comment]
@MKrieger29 tu peux checker ça stp ? Dans la base, les Arvor_D font il parti du network argo deep ?
Merci,

**Comment by MKrieger29** [comment]
Le ticket a été soumis il y a quelques mois, donc les ref en question se sont mises à jour par la suite, j'imagine. 
J'ai regardé le script, il faut que la ptf soit REGISTERED, OPERATIONAL, INACTIVE ou CLOSED pour avoir automatiquement le network Argo Deep. Si PROBABLE ou CONFIRMED, pas d'allocation automatique du network Argo Deep. 
Difficile de dire si c'était ça le soucis avec ces ptf en particulier, mais on peut l'imaginer.
